[go]
b = "build"
i = "install"
r = "run"
test = "test -v"
t = "test -v"
ta = "test -v ./..."
tr = "test -run"

[docker]
l = "logs"
i = "image"
c = "container"

[kubectl]
c = "create"

[git]
l = "log --graph --oneline"

[m]
s = "sleep"
l = "lock"
