[go]
b = "build"
i = "install"
r = "run"
test = "test -race -v"
t = "test -race -v"
ta = "test -race -v ./..."
tr = "test -race -v -run"

[docker]
l = "logs"
i = "image"
c = "container"
n = "network"
p = "push"

[kubectl]
c = "create"

[git]
l = "log --graph --oneline"

[m]
s = "sleep"
l = "lock"

[cargo]
b = "build"
r = "run"
