[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'htm']
on_i = 1

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
on_i = 1

[[plugins]]
repo = 'mattn/jscomplete-vim'
on_ft = ['js']
on_i = 1

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1
